"""Initial schema

Revision ID: 2d421ce02721
Revises: dfef73e04fc3
Create Date: 2025-06-27 15:55:13.449250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d421ce02721'
down_revision: Union[str, Sequence[str], None] = 'dfef73e04fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('dataset_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('size_mb', sa.Float(), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('crs', sa.String(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    op.create_index(op.f('ix_datasets_dataset_id'), 'datasets', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasets_dataset_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
